require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 3.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'app/models/application_record.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments